module.exports = {
  printWidth: 100,
  singleQuote: false,
  semi: true,
  trailingComma: "all",
  tabWidth: 2,
  plugins: ["prettier-plugin-tailwindcss"],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  importOrderGroupOrder: [
    "builtin",
    "external",
    "internal",
    "parent",
    "sibling",
    "index",
    "object",
    "type",
    "unknown",
  ],
  ignoreNodeModules: true,
};
